edx/journals

journals/apps/journals/models.py, journals/apps/search/views.py, journals/settings/local.py
Three changes:
1. fix many pylint warnings
2. fixed broken search for document contents
3. added is_staff check in has_access() check to grant staff permission to JournalPage
=> fix broken search, pylint cleanup, staff access to Journal

journals/apps/api/v1/views.py, journals/settings/base.py
- Add additional logging
- Allow all hosts
=> Additional Logging to JournalAccess api

Makefile, journals/apps/api/v1/views.py, journals/apps/journals/management/commands/gather_videos.py, journals/apps/journals/templates/header.html, journals/settings/base.py, provision-journal.sql, provision-journals.sh, requirements/base.txt, test.sh
Features 
- Running make dev.provision will build out all necessary services. 
- Adds JWT authentication to Journals
=> Automate Journal provisioning

journals/apps/api/filters.py
- If a user has renewed their access to a given journal they may have
multiple JournalAccess records for a given journal. If 'get_latest' is
set to true, JournalAccess api will now only return one JournalAccess
record per journal per user.
- In other words, for a given user-journal pair there should only be one
JournalAccess record returned.
- In the case where a user-journal pair has multiple journal access
records, return the access record with the latest expiration date.
=> Add get_latest query param to JournalAccess API

journals/apps/core/management/commands/create_org.py, journals/apps/core/management/commands/create_site.py
Also contains create_site fixes that didn't make it into the last PR.
=> Create org via management command

Makefile, journals/apps/core/management/commands/create_site.py, journals/apps/core/management/commands/create_themed_sites.py
Similar to ecommerce and lms, with this we are able to create new sites via a themed configuration file.
=> Add mgmt cmd to add sites from themes

requirements/test.txt
This PR bumps bok-choy version.
=> bumped bok-choy version

journals/apps/core/management/commands/create_site.py, journals/apps/core/management/commands/create_themed_sites.py
and remove issuer from oauth configuration as it's no longer needed causing issues on sandbox
=> Add support for creating Organization 

journals/apps/core/wagtail_hooks.py, journals/apps/journals/models.py
This PR has defined custom wagtail hooks to show pages and summaries according to user permissions on wagtail admin home page.
=> WL-1566: defined custom wagtail hooks

journals/apps/core/wagtail_hooks.py, journals/apps/journals/blocks.py, journals/apps/journals/models.py, journals/apps/journals/static/js/video/chooser/video-chooser.js, journals/apps/journals/templates/videos/chooser/chooser.html, journals/apps/journals/templates/videos/chooser/chooser.js, journals/apps/journals/templates/videos/chooser/results.html, journals/apps/journals/templates/videos/chooser/video_chooser.html, journals/apps/journals/templates/videos/chooser/video_chosen.js, journals/apps/journals/templates/videos/list.html, journals/apps/journals/templates/wagtailadmin/shared/collection_chooser.html, journals/apps/journals/templatetags/wagtail_tags.py, journals/apps/journals/urls.py, journals/apps/journals/video_chooser.py, journals/apps/journals/widgets.py, journals/urls.py
This PR has changes to add ability to choose videos from page editor. User's are allowed to choose only from those video collections where they have either `change` or `Delete` permissions. User can search videos in the video chooser dialog.
=> WL-1684: Ability to choose a video

journals/apps/core/models.py
make user_has_access a property
=> Correctly check user permission for admin access

journals/settings/base.py, requirements/base.txt
needed by ansible/gocd scripts
=> add edx-django-release-util requirement

journals/apps/journals/management/commands/gather_videos.py, journals/apps/journals/models.py, journals/apps/journals/permissions.py, journals/apps/journals/templates/videos/import_video.html, journals/apps/journals/templates/videos/index.html, journals/apps/journals/urls.py, journals/apps/journals/views.py
This PR has changes to add ability to import videos from wagtail admin. 
1. Modified `gather_videos` management command to import videos by single journal or multiple journals
2. Created a wagtail admin view to select a journal to import videos into
3. Added loading spinner and disabled `Import Video` button until we have completion status.
4. Completion status is display on the right panel
=> WL-1686: Added ability to import videos from wagtail admin

journals/apps/api/serializers.py, journals/apps/api/v1/theming/serializers.py, journals/apps/api/v1/theming/views.py, journals/apps/api/v1/urls.py
SiteInfo API returns alls information necessary for the frontend to load
correctly. It includes user, theme, and site info.
=> Adds a /siteinfo API

journals/settings/base.py, requirements/base.txt
=> Add metrics for requests.

journals/apps/journals/journal_page_helper.py
Pass journalAboutId and use the same serializer we are using for Pages
=> Fix previews on frontend

journals/apps/api/serializers.py
Needed by frontend app to dynamically show CMS menu
=> Add can_access_admin to UserSerializer

journals/apps/core/wagtail_hooks.py, journals/apps/journals/admin/__init__.py, journals/apps/journals/admin/django_admin.py, journals/apps/journals/api_utils.py, journals/apps/journals/forms.py, journals/apps/journals/management/commands/gather_videos.py, journals/apps/journals/management/commands/publish_journals.py, journals/apps/journals/models.py, journals/apps/journals/permissions.py, journals/apps/journals/templates/journals/admin_index.html, journals/apps/journals/templates/journals/list.html, journals/apps/journals/urls.py, journals/apps/journals/utils.py, journals/apps/journals/views.py, journals/apps/journals/wagtailadmin/admin.py, journals/apps/journals/wagtailadmin/forms.py, journals/apps/journals/wagtailadmin/views.py, package-lock.json
Requirement was to create a UI to manipulate Journal from CMS that will run Management command at Backend, so this PR contains.
- Added management command to update Journal
- Added Menu for Journals in CMS
- Added Index view for Journal  that displays shows list of journal relevant to user. price, currency and status fetched from discovery.
- Added a Edit View to Edit only name, status and videos config. status fetched form discovery. Performing functionality using management command.
- Added  a create view to create new journal, for relevant organizations only. Super user can add new Journal to any Organization. This view is also working with help of management command.
-  Added migration to make sure each organization have a unique site.
=> Hammad/WL-1688 create UI for publish_journals mgmt command

journals/apps/api/serializers.py, journals/apps/journals/models.py
relies on related PRs:
discovery: https://github.com/edx/course-discovery/pull/1543
edx-platform: https://github.com/edx/edx-platform/pull/18888
=> pass about_page_id to discovery instead of slug

requirements/base.txt
=> Upgrade edx-django-utils.

journals/apps/api/filters.py, journals/apps/api/serializers.py, journals/apps/journals/blocks.py, journals/apps/journals/models.py, journals/apps/journals/templates/blocks/xblockvideo.html
Depends on LMS PR: https://github.com/edx/edx-platform/pull/18738
=>  WL-1687 | Added user journal access check for videos

journals/apps/api/v1/theming/views.py, journals/settings/production.py
Was using request port which didn't take into account proxies.
=> Fix siteinfo port selection

journals/apps/core/tests/factories.py, journals/apps/journals/handlers.py, journals/apps/journals/tests/test_journal_about_page.py
This PR added unit tests to test journal about page structure.
=> WL-1742: unit tests to test journal about page structure

journals/apps/journals/models.py, journals/settings/base.py, requirements/base.txt
This PR has changes to restrict only pdf documents uploads via document chooser block.
=> WL-1787: restrict to upload only pdf documents

journals/apps/journals/wagtailadmin/views.py, journals/urls.py
This PR has changes to restrict page move destinations to only those where user has permissions.
=> WL-1759: Restricted page move destinations

journals/apps/journals/models.py
Needed by journals-frontend PR: https://github.com/edx/journals-frontend/pull/57
=> Return organization in JournalIndexPage api

journals/apps/journals/management/commands/publish_journals.py
Journal publishing fixes
Log errors when pushing to discovery and ecommerce during publishing.
Also pass updated Organization dict to discovery needed for api change.
Depends on https://github.com/edx/course-discovery/pull/1577
=> Journal publishing fixes

requirements/base.txt
Pins urlib3 to fix dependency issue.
=> Pin urllib3

journals/settings/base.py, requirements/base.txt
=> ARCH-255: Upgrade edx-drf-extensions to 2.0.0.

journals/apps/core/management/commands/create_site.py, journals/apps/journals/admin/django_admin.py
expose JournalIndexPage in django-admin in case we need to delete, enhance create_site mgmt command so it correctly associates site with an org
=> additions to WL-1845

journals/apps/journals/handlers.py, journals/apps/journals/journal_page_helper.py, journals/apps/journals/models.py, journals/apps/journals/templates/wagtaildocs/documents/confirm_delete.html, journals/apps/journals/templates/wagtailimages/images/confirm_delete.html, journals/apps/journals/utils.py
- moved common code used in JournalImage and JournalDocument into new mixin ReferencedObjectMixin
- moved signal handlers into handlers.py where other signal handlers live
- created method to find instance in block fields
=> refactor code for maximum reuse

journals/apps/journals/api_utils.py, journals/apps/journals/models.py
add error handling so can display journal index page and journal about pages even if lms is not running
=> handle connection errors to LMS

.travis.yml, .travis/Dockerfile, openedx.yaml
=> Upgrade from Python 3.5 to 3.6
