edx/journals

- README.rst
- journals/apps/social_auth/strategies.py
- journals/settings/base.py
- journals/settings/local.py
By default, the social auth plugin we're using to authenticate with LMS only checks the settings file and can't use site configuration. I've copied the functionality from ecommerce to check site config for oauth.
This also updates the documentation for match the changes.
> Add Social Auth config by Site Config

- journals/apps/core/views.py
- journals/apps/journals/models.py
- journals/urls.py
Creates URL path that allows login prior to forwarding. Copying the function docs here:
Used to require the user to log in through the journals service (thus creating an account in Journal for a new user) before being forwarded to the destination URL. This is necessary for verifying a user has an account in Journals so a purchase can be linked to that account.
When generating a basket URL for a product that includes Journal access, it should be created via the following pattern:
```
encoded_basket_url = urllib.parse.quote("<basket_url>")
display_url = "<journals_domain>/require_auth?forward={}".format(encoded_basket_url)
```
> Create forwarding view that requires auth

- Dockerfile-journals
- journals/apps/journals/models.py
Ubuntu 16.04 doesn't package Python 3.6 and that's what we're using as
a base OS everwhere.
> Rollback to Python 3.5

- journals/settings/local.py
The recent changes to the logging settings in #33 broke logging in the docker devstack since
docker doesn't support the syslog socket. Copied code from ecommerce:
https://github.com/edx/ecommerce/blob/master/ecommerce/settings/devstack.py#L11
> Fix logging regression in docker

- provision-journal.sql
- Journal provisioning was failing due to an extra line in
provision-journal.sql which through a value and row number mismatch
error
> Fix error in journal provisioning

- journals/apps/journals/models.py
Ints are easier to pass across services, requiring us to only convert
to timedeltas occasionally instead of always.
> Change access_length to an int to match discovery

- journals/apps/journals/blocks.py
- journals/apps/journals/models.py
- journals/apps/journals/tests/test_blocks.py
- requirements/test.txt
This PR has changes to provide content authors ability to add `RawHTMLBlock` to journal page. It modifies `JournalRawHTMLBlock` to strip `script`, `frame`, `iframe` and `link` tags from input.
> WL-1630: added RawHTMLBlock to journal page

- journals/apps/core/wagtail_hooks.py
- journals/apps/journals/models.py
- journals/apps/journals/templates/wagtailadmin/shared/collection_chooser.html
- journals/apps/journals/templatetags/wagtail_tags.py
- journals/settings/base.py
This PR has changes to restrict image and document chooser dialogs show only those images/documents which belongs to a collection where user has `add` or `change` permissions in wagtail admin. It has changes to display only those collections in `Collections` drop-downs inside document/image chooser dialogs where user has `add` or `change` permissions.
> WL-1563: changes to make document and images collection selection site specific

- journals/apps/journals/management/commands/publish_journals.py
- journals/apps/journals/models.py
journals management command `publish_journals` was sending `Journal`'s name to **e-commerce** and **discovery** services. but we were expecting to send `JournalsAboutPage`'s title to **discovery** and **e-commerce** like we do on Edit `JournalAboutPage`.
> sending JournalsAboutPage title instead of Journal name to the other services

- journals/apps/api/v1/content/urls.py
- journals/apps/journals/journal_page_helper.py
- journals/apps/journals/models.py
- journals/settings/base.py
- journals/urls.py
- Enabled the wagtail 'pages' api which lets you query journal pages
- Added a custom field to AboutPage to get the hierarchical structure of
the journal
Usage (on local devstack):
- To get a json blob of all pages in the Journals service go to:
http://localhost:18606/api/v1/content/pages/
- There are a variety of filtering and ordering options. For more
information see the wagtail documentation:
http://docs.wagtail.io/en/v1.7/advanced_topics/api/v2/usage.html
- To get the hierarchical structure of a journal go to:
http://localhost:18606/api/v1/content/pages/?slug=JOURNAL-ABOUT-PAGE-SLUG&type=journals.JournalAboutPage&fields=get_journal_structure
Remaining Work:
- Testing for this API endpoint
> Create AboutPage API with Journal Structure Field

- journals/apps/api/v1/theming/filters.py
- journals/apps/api/v1/theming/serializers.py
- journals/apps/api/v1/theming/views.py
- journals/apps/api/v1/urls.py
- Create Endpoint to access Site Branding information
Usage:
- Path to API Endpoint: /api/v1/sitebranding/
- Query Params:
- theme_name: Name of site branding theme
- site_name: Name of associated site
- hostname: Hostname for assocated site
Remaining Work:
- Tests
> Create Site Branding API

- journals/settings/base.py
- journals/settings/local.py
- requirements/base.txt
Add CORS library to handle cross domain requests to service. Also adds
the port from our development server to the local whitelist.
> Allow CORS requests to APIs

- journals/apps/api/filters.py
- journals/apps/api/v1/content/tests/test_content_api.py
- journals/apps/api/v1/content/urls.py
- journals/apps/api/v1/content/views.py
- journals/apps/core/tests/factories.py
- journals/apps/core/tests/utils.py
- journals/apps/journals/models.py
API now removes all Journal Pages that is attached to a Journal that the user doesn't have access to.
> Add authorization checking on Wagtail Pages API

- provision-journal.sql
The journal ecommerce api was changed from 'journal/api/v1' to
'journals/api/v1'.  This change is to accomadate that change.
Note: This change is dependent on:
https://github.com/edx/ecommerce/pull/1790
> Integrate with New Ecommerce API Path

- journals/apps/api/v1/preview/views.py
- journals/apps/journals/journal_page_helper.py
- journals/apps/journals/models.py
Currently our page structure and next/prev logic does not take into account whether pages are live or not and it should.
This PR has the changes to conditionally return only the published pages in the appropriate calls.
NOTE:
In testing, there was an added complexity that I didn't realize. You can have published pages beneath a parent that is not published, which makes things rather tricky. For example in this scenario all pages are published except Chapter 2:
```
Chapter 1:
Page 1-1
Chapter 2: (unpublished)
Page 2-1
Page 2-2
Chapter 3:
Page 3
```
In the TOC view, we'd want this to display as:
```
Chapter 1:
Page 1-1
Page 2-1
Page 2-2
Chapter 3:
Page 3
```
Since Chapter 2 is not published we want it's children to display at the same level as the other chapters.
I struggled to get this …
> Change navigation to only include live (published) pages

- journals/apps/core/wagtail_hooks.py
- journals/apps/journals/templates/wagtailadmin/commands.html
- journals/apps/journals/views.py
This PR has changes to provide ability to run management commands from within wagtail admin interface for staff users.
To test it
1) Go to `Settings -> Run Commands` in wagtail admin of journals.
2) Select the command to run and hit `Run Command` button.
3) Output of the command should be visible in `Command Status` section at the bottom.
> WL-1727: Added ability to run management commands from within wagtail admin

- journals/apps/journals/models.py
previews were broken because we were saving the journal page during the call to get_journals() from serve() method. Seems the only reliable way to check if page is live is to make sure page_ptr_id is not None. The .live property always returns true which is not what I expected
> don't save page when previewing

- journals/apps/journals/handlers.py
This handler is not necessary as wagtail already has a built in listener for all models. This was causing Videos to be indexed twice every time a Video model is added/updated.
> remove post_save video indexer as it's redundant

- journals/apps/api/v1/theming/views.py
Due to reverse proxies and other network things, we should use the
request's scheme for the server rather than the one specified in sites.
We also won't show ports on standard port calls to keep URLs pretty.
> Fix HTTP/HTTPS issue.

- journals/settings/base.py
- journals/settings/local.py
Current setup is breaking when headers are added by webserver config.
> Move allow credentials headers to dev only

- journals/settings/base.py
- requirements/base.txt
From edx-drf-extensions:
1. EnsureJWTAuthSettingsMiddleware: Ensures proper JWT auth settings
for endpoints.
2. JwtAuthCookieMiddleware: Combines the JWT auth cookie parts into a
JWT auth cookie.
ARCH-233
> ARCH-233: Add JWT Auth Middleware.

- journals/apps/journals/models.py
- journals/settings/base.py
We limit our file upload size via wagtail, but Elasticsearch has a 10MB limit of content uploaded to it. So we need to make sure documents (which are base64 encoded and larger than original file) and video transcripts are limited to that size. 
Rather than rejecting, we'll upload the first 10MB of document contents or video transcript and ignore the rest.
> limit size of attachment uploaded to elasticsearch

- journals/apps/journals/models.py
We shouldn't be directly creating JournalAboutPages from the Pages UI in wagtail as it can cause problems if the underlying Journal hasn't yet been created. Instead, JournalAboutPages get created automatically when you create a Journal via the Journal section of wagtail.
> don't allow creating a JournalAboutPage directly from page menu

- journals/apps/journals/models.py
- journals/settings/base.py
Seeing lots of read timeouts in splunk when trying to upload largeish documents. This bumps the default timeout up to try and avoid.
> increase read/write timeout for elasticsearch

- journals/apps/journals/admin/django_admin.py
Add Videos to django-admin in case we need to delete any, which is currently not supported in the wagtail UI.
> add Videos to django-admin

- journals/settings/base.py
When JWT cookies are required, there will be some work needed to make this work.  
See "[ARCH-266: Backend: Enable JWT Cookies in remaining IDAs.](https://openedx.atlassian.net/browse/ARCH-266)"
> ARCH-262: Reverts addition of JwtAuthCookieMiddleware

- journals/apps/journals/journal_page_helper.py
Removing frontend_enabled waffle switch
========================================
There was code that was checking frontend_enabled waffle switch in journals-service to determine whether to render using the frontend app or backend.
It was temporary as we were transitioning to the frontend-app, but now that we are done we have remove the switch and make rendering to the frontend the default.
> WL-1841 Removing frontend_enabled waffle switch

- journals/apps/core/__init__.py
- journals/apps/core/apps.py
- journals/apps/core/handlers.py
- journals/apps/core/tests/test_handlers.py
This PR has changes to disable user's notification preferences by default.
To test it.
1. Signup on journals.
2. As an admin user changes role of newly created user to have editors or moderator privileges
3. Log in with newly created user and make sure check boxes under [notifications preferences are](http://localhost:18606/cms/account/notification_preferences/) unchecked.
> WL-1848: disable notification preferences by default

- journals/apps/core/middleware.py
- journals/apps/core/tests/test_middleware.py
This PR sets `BASE_URL` setting by geting scheme and host from request to fix issue reported in WL-1844.
> WL-1844: set BASE_URL setting by geting scheme and host from request

- journals/apps/journals/static/pdf_js/web/viewer.html
"Open File" option Removed from pdf.js
========================================
There was "Open File" menu option in the pdf viewer.
Changed the pdf.js code in journals to never display the Open File button.
> "Open File" option Removed from pdf.js

- journals/apps/journals/templates/403.html
update existing 403 page to remove the old header as we don't want it anymore. This only gets shown if someone tries to access something in wagtail that they don't have permissions for
> update 403 page to remove old header

- journals/settings/utils.py
get_env_setting is used in settings when apps aren't loaded yet.
Build pipeline has been failing since this import was added. Not reproducible locally, so we'll need to verify this fixes it once merged.
> Dynamically import SiteConfig in utils

- journals/apps/core/management/commands/create_site.py
- journals/apps/journals/admin/django_admin.py
- journals/apps/journals/journal_page_helper.py
- journals/apps/journals/models.py
- journals/apps/journals/templatetags/wagtail_tags.py
Disable dangerous creation/deletion options in Journal Editor
=====================================================================
As we create and delete Journals from "Journals" panel (which in turn
creates appopriate Index and About Pages), So restricted editors to
directly to create or delete these types of pages through the Wagtail UI.
> Hammad/WL 1845 Disable dangerous creation/deletion options in Journal Editor

- journals/apps/api/v1/search/views.py
- journals/apps/api/v1/tests/test_search_api.py
test_search_across_multiple_journals_with_AND_operator is flaky
====================================================================
The test_search_across_multiple_journals_with_AND_operator test in the
journals IDA is flaky. It was failing on multiple PRs and a rerun fixed
it.
`and` was overridden to work as `phrase` type search but test was testing it As `and`
Logic. Now test modified according to "phrase" type search.
also all `contains` are converted to `icontains` to support case insensitive testing.
> WL-1851| test_search_across_multiple_journals_with_AND_operator is flaky

- journals/apps/journals/models.py
This PR has changes to expose  journal's `access_length` property in content/pages API.
> WL-1866: Exposed journal's `access_length` in API

- journals/apps/core/wagtail_hooks.py
- journals/apps/journals/models.py
- journals/apps/journals/static/js/lib/halo_codeblock_plugin.js
- journals/apps/journals/templates/wagtailadmin/halo/code_block.html
- journals/apps/journals/templates/wagtailadmin/halo/code_inserted.js
- journals/apps/journals/urls.py
- journals/apps/journals/wagtailadmin/views.py
This PR has changes to add code block insertion support in wagtail admin's rich text editor.
To test 
1. add new code block
move pointer in text editor to a point where you want to add code block and click `CodeBlock` button. Enter code in the input box of popup window and hit `Add code block` button
2. Edit existing code block
Move pointer to anywhere in the existing code block it should highlight `CodeBlock` button. Click the `CodeBlock` button and edit your code block
3. Convert any text in the rich text editor
Select the text you want to convert into a code block and hit `CodeBlock` button.
> WL-1853: added code block support to rich text editor
